version: "3"
services:
  api:
    image: webapp
    container_name: mywebapp
    build:
      context: .
      dockerfile: D:\Eclipse Workspace\OnlineShoppingAssessment\DockerTomcat\Dockerfile
    ports:
      - 80:8080
  database:
    image: mysql
    container_name: jspmysql
    build:
      dockerfile:D:\Eclipse Workspace\OnlineShoppingAssessment\DockerMySQL\Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sms
    ports:
      - "6703:3306"
    volumes:
      - .DockerMySQL/jsp_backup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
volumes:
    db_data: